# General Jekyll Config
url: http://pennea.org
lsi: false
exclude: [LICENSE, CNAME, README.md, TODO.md, .gitignore, Gemfile, Gemfile.lock]
permalink: /:categories/:year/:month/:day/:title/

# Build options
future: true
